(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
"use strict";var _main=_interopRequireDefault(require("./ripples/main.js"));function _interopRequireDefault(a){return a&&a.__esModule?a:{default:a}}document.addEventListener("DOMContentLoaded",function(){(0,_main["default"])()});
},{"./ripples/main.js":3}],2:[function(require,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports["default"]=void 0;function attachRippleEventListener(a){function b(a,b,c,d,e){function f(){a.globalAlpha-=.05,a.globalAlpha=+a.globalAlpha.toFixed(2),a.clearRect(0,0,c,d),a.fillStyle=b,a.fillRect(0,0,c,d),0>=a.globalAlpha&&(a.clearRect(0,0,c,d),a.globalAlpha=1,clearInterval(g),g=null,e.parent().click())}a.globalAlpha=1,g||(g=setInterval(f,20))}function c(a){function c(){k.clearRect(0,0,n,m),k.fillStyle="rgba(0,0,0,0)",k.fillRect(0,0,n,m),k.beginPath(),k.arc(g,i,p,0,2*Math.PI),k.fillStyle=l,k.fill(),k.closePath(),p+=5,p>o+50&&(clearInterval(h),h=null,e&&b(k,l,n,m,d),f=!0)}f=!1,e=!1,a.stopImmediatePropagation();var d=$(this).siblings(".ripples-action"),g=a.pageX-d.offset().left,i=a.pageY-d.offset().top,j=d[0],k=j.getContext("2d"),l=d.attr("data-backgroundColor"),m=d.parent().height(),n=d.parent().width(),o=d.parent().height();d.width()>o&&(o=d.width()),k.globalAlpha=1,k.clearRect(0,0,n,m);var p=0;h||(h=setInterval(c,1e3/o))}function d(){var a=$(this).siblings(".ripples-action"),c=a[0].getContext("2d"),d=a.attr("data-backgroundColor"),g=a.height(),h=a.width();f&&b(c,d,h,g,a),e=!0}var e=!1,f=!1,g=null,h=null;a.find(".ripples-content-container").on("mousedown",c),a.find(".ripples-content-container").on("mouseup",d),a.find(".ripples-content-container").on("click",function(a){a.stopImmediatePropagation()})}var _default=attachRippleEventListener;exports["default"]=_default;
},{}],3:[function(require,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports["default"]=void 0;var _styles=_interopRequireDefault(require("./styles/styles.js")),_replaceContent=_interopRequireDefault(require("./replaceContent.js")),_attachRippleEventListener=_interopRequireDefault(require("./eventListener/attachRippleEventListener.js"));function _interopRequireDefault(a){return a&&a.__esModule?a:{default:a}}function initializeRipples(){(0,_styles["default"])();var a=$(".ripples").toArray().map(function(a){return $(a)});a.forEach(function(a){(0,_replaceContent["default"])(a),(0,_attachRippleEventListener["default"])(a)})}var _default=initializeRipples;exports["default"]=_default;
},{"./eventListener/attachRippleEventListener.js":2,"./replaceContent.js":4,"./styles/styles.js":5}],4:[function(require,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports["default"]=void 0;function replaceContent(a){var b=a.html(),c="rgba(255,255,255,0.5)";a.hasClass("ripples-dark")&&(c="rgba(0,0,0,0.3)");var d=a.css("padding");a.css("padding","0px"),a.addClass("ripples-no-padding");var e="<canvas class='ripples-action' data-backgroundColor='"+c+"'></canvas>";a.html(e+"<div class='ripples-content-container'>"+b+"</div>"),a.find(".ripples-content-container").css("padding",d);var f=a.find(".ripples-action")[0];f.height=a.outerHeight(),f.width=a.outerWidth()}var _default=replaceContent;exports["default"]=_default;
},{}],5:[function(require,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports["default"]=void 0;function addStyles(){$("body").prepend("<style>\n        /* Actions */\n        .ripples-action {\n            display: block;\n            position: absolute;\n            z-index: 2;\n            padding: 0 !important;\n            margin: 0 !important;\n        }\n        /* The element itself */\n        .ripples {\n            position: relative;\n            overflow: hidden;\n        }\n\n        /* Ripples content container */\n        .ripples-content-container {\n            display: inline-block;\n            position: relative;\n            background-color: transparent !important;\n            z-index: 3;\n        }\n        \n        /* button shadow */\n        .ripples-btn {\n            box-shadow: 0px 2px 5px #888888;\n            border: none !important;\n            cursor: pointer;\n        }\n        .ripples-btn:hover {\n            box-shadow: 0px 4px 6px #888888;\n        }\n        .ripples-no-padding {\n            padding: 0 !important;\n        }\n    </style>")}var _default=addStyles;exports["default"]=_default;
},{}]},{},[1]);
